TRANSLATIONS_DE = {
    'nummer': 'number',
    'der nummer': 'number',
    'auftrag': 'order',
    'to-do': 'to do',
    'to do': 'to do',
    'todo': 'to do',
    'lange': 'length',
    'länge': 'length',
    'laenge': 'length',
    'besitzer': 'owner',
    'benutzer': 'user',
    'benutzername': 'username',
    'benutzernamen': 'username',
    'passwort': 'password',
    'besitzerin': 'owner',
    'inventur': 'inventory',
    'system': 'system',
    'dem anderen system': 'the other system',
    " \u00c4ndern von ToDo - anderer Nutzer": "Change of ToDo - other users",
    "\"Fertig\" als Status": "\"Fertig\" als Status",
    "\"Haus1234\" als Passwort": "\"Haus1234\" als Passwort",
    "\"Test\"": "\"Test\"",
    "Alice": "Alice",
    "Anfrage": "Anfrage",
    "Apfel": "Apple",
    "Auftrag": "order",
    "Auftrag sehen": "See order",
    "Ausgabe": "output",
    "Auto": "automobile",
    "Benutzer": "user",
    "Benutzernamen": "username",
    "Berechtigung": "authorization",
    "Besitzer": "owner",
    "Besitzerin": "owner",
    "Bild": "picture",
    "Bob": "bob",
    "CSV": "CSV",
    "Dach": "Roof",
    "Datei": "file",
    "Detail": "detail",
    "Details": "Details",
    "Ein": "A",
    "Email": "E-mail",
    "Frage": "question",
    "Fu\u00dfball": "Soccer",
    "Gegeben": "Given",
    "Inhalt": "content",
    "Inventur": "inventory",
    "Irgendwas kryptisches": "Something cryptic",
    "Kann Auftr\u00e4ge l\u00f6schen": "Can delete orders",
    "Kann Auftr\u00e4ge sehen": "Can see orders",
    "Kohle": "coal",
    "Lade": "Ark",
    "Laden": "load",
    "List": "Cunning",
    "Liste": "list",
    "L\u00e4nge": "length",
    "M2M Model": "M2M model",
    "M2M Relation": "M2M relation",
    "MP3-Datei": "MP3 file",
    "Mein Text": "Mein Text",
    "Name": "Surname",
    "Namen": "Names",
    "Nummer": "number",
    "Nutzer": "Users",
    "PK": "PK",
    "Passwort": "password",
    "Peter": "Peter",
    "Photoshop": "Photoshop",
    "Photoshop-Datei": "Photoshop file",
    "Sammlung": "collection",
    "Spieler": "player",
    "Status": "Status",
    "System": "system",
    "Text": "text",
    "Text-Datei": "Text file",
    "To-Do": "To do",
    "To-Do's": "To-do's",
    "To-Dos": "To-dos",
    "ToDo": "to do",
    "ToDo's": "ToDo's",
    "Todo": "To do",
    "Todos": "Todos",
    "Tr\u00e4ger": "carrier",
    "Und die folgenden To-Do": "And the following to-do",
    "Und die folgenden To-Dos": "And the following to-dos",
    "Und folgende To-Dos": "And the following to-dos",
    "Wenn": "If",
    "Wenn Alice die Liste der Auftr\u00e4ge holt": "When Alice fetches the list of orders",
    "Wenn Alice einen Auftrag erstellt": "When Alice creates an order",
    "Wenn Alice einen Auftrag l\u00f6scht": "When Alice deletes an order",
    "Wenn die Liste der Auftr\u00e4ge geholt wird": "When the list of orders is fetched",
    "Wenn ein Auftrag erstellt wird": "When an order is created",
    "Wenn ein Auftrag mit dem Namen \"Test\" erstellt wird": "When a job named \"Test\" is created",
    "Word": "Word",
    "Word-Datei": "Word file",
    "Zeit": "time",
    "Zuhause": "Zuhause",
    "a@local.local": "a@local.local",
    "add order": "add order",
    "aktualisieren": "To update",
    "aktualisiert": "aktualisiert",
    "alice": "alice",
    "als": "als",
    "angepasst": "angepasst",
    "brauchen": "need",
    "change order": "change order",
    "content": "content",
    "das Passwort": "the password",
    "dem": "the",
    "dem Benutzernamen": "the username",
    "dem Benutzernamen Alice": "dem Benutzernamen Alice",
    "dem Benutzernamen Bob": "the username Bob",
    "dem Benutzernamen alice": "the username alice",
    "dem Besitzer": "the owner",
    "dem Codenamen": "the code name",
    "dem Dach": "the roof",
    "dem Inhalt": "the content",
    "dem Laden": "the store",
    "dem Namen": "the name",
    "dem Namen \"['123'": "the name \"['123'",
    "dem Namen Alice": "the name Alice",
    "dem Namen alice": "the name alice",
    "dem PK": "the PK",
    "dem Passwort Haus1234": "the password Haus1234",
    "dem Text": "the text",
    "dem Text todo1": "the text todo1",
    "dem anderen System": "the other system",
    "den Auftr\u00e4gen": "the orders",
    "den Benutzerberechtigungen": "the user permissions",
    "den Benutzernamen Peter": "the username Peter",
    "den Berechtigungen": "the permissions",
    "den Namen Alice": "the name Alice",
    "den Sammlungen": "the collections",
    "den To-Do's": "the to-do's",
    "den ToDo's": "the to-do's",
    "den Todos": "the todos",
    "der": "the",
    "der Benutzerberechtigung": "the user authorization",
    "der Datei": "of the file",
    "der Email": "the e-mail",
    "der Email a@local.local": "the email a@local.local",
    "der Fu\u00dfball": "the football",
    "der Kohle": "the coal",
    "der Nummer": "number",
    "der Sammlung": "Of the collection",
    "die": "the",
    "drei": "three",
    "ein": "a",
    "ein folgende To-Do": "a following to-do",
    "eine Photoshop Datei": "a Photoshop file",
    "einen": "one",
    "einer Sammlung": "a collection",
    "erstellen": "create",
    "erstellt": "created",
    "essen": "eat",
    "fahren": "drive",
    "file": "file",
    "folgenden": "following",
    "geben": "give",
    "gel\u00f6scht": "gel\u00f6scht",
    "ge\u00e4ndert": "ge\u00e4ndert",
    "holen": "to fetch",
    "holt": "get",
    "ich": "ich",
    "keine Kohle": "no money",
    "l\u00f6schen": "Clear",
    "l\u00f6scht": "clears",
    "mehr": "more",
    "mein": "my",
    "mit": "With",
    "name": "name",
    "number": "number",
    "nur": "just",
    "nutzen": "use",
    "oder": "or",
    "order.change_order": "order.change_order",
    "order.view_order": "order.view_order",
    "order.view_order und order.change_order": "order.view_order and order.change_order",
    "owner": "owner",
    "sein": "be",
    "sieben": "seven",
    "sollen": "should",
    "starten": "start",
    "text": "text",
    "the list": "the list",
    "value": "value",
    "view order": "view order",
    "wenig": "little",
    "weniger": "Less",
    "werden": "become",
    "wird": "becomes",
    "zehn": "ten",
    "zwanzig": "twenty",
    "zwei": "two",
    "\u00c4ndern von ToDo -        anderer Nutzer": "Change of ToDo - other users",
    "\u00c4ndern von ToDo -   -  -   anderer Nutzer": "Changing ToDo - - - of other users",
    "\u00c4ndern von ToDo - anderer Nutzer": "Change of ToDo - other users",
    "\u00e4ndern": "to change"
}

TRANSLATIONS_EN = {
    "7-Zip": "7-zip",
    "Auftrag": "Auftrag",
    "Bash": "Bash",
    "Benutzer": "Benutzer",
    "C": "C",
    "C++": "C++",
    "CSS": "CSS",
    "CSV": "CSV",
    "Can add Auftrag": "Kann Auftrag hinzuf\u00fcgen",
    "Can add content type": "Kann Inhaltstyp hinzuf\u00fcgen",
    "Can add group": "Kann Gruppe hinzuf\u00fcgen",
    "Can add log entry": "Kann Log-Eintrag hinzuf\u00fcgen",
    "Can add permission": "Kann Berechtigung hinzuf\u00fcgen",
    "Can add session": "Kann Sitzung hinzuf\u00fcgen",
    "Can add user": "Kann Benutzer hinzuf\u00fcgen",
    "Can change Auftrag": "Kann Auftrag \u00e4ndern",
    "Can change content type": "Kann Inhaltstyp \u00e4ndern",
    "Can change group": "Kann die Gruppe \u00e4ndern",
    "Can change log entry": "Kann Log-Eintrag \u00e4ndern",
    "Can change permission": "Kann die Berechtigung \u00e4ndern",
    "Can change session": "Kann die Sitzung \u00e4ndern",
    "Can change user": "Kann den Benutzer \u00e4ndern",
    "Can delete Auftrag": "Kann Auftrag l\u00f6schen",
    "Can delete content type": "Kann Inhaltstyp l\u00f6schen",
    "Can delete group": "Kann Gruppe l\u00f6schen",
    "Can delete log entry": "Kann Log-Eintrag l\u00f6schen",
    "Can delete permission": "Kann die Berechtigung l\u00f6schen",
    "Can delete session": "Kann Sitzung l\u00f6schen",
    "Can delete user": "Kann Benutzer l\u00f6schen",
    "Can view Auftrag": "Kann Auftrag ansehen",
    "Can view content type": "Kann Inhaltstyp anzeigen",
    "Can view group": "Kann Gruppe anzeigen view",
    "Can view log entry": "Kann Log-Eintrag anzeigen",
    "Can view permission": "Kann die Berechtigung anzeigen",
    "Can view session": "Kann Sitzung anzeigen",
    "Can view user": "Kann Benutzer anzeigen",
    "ContentType": "Inhaltstyp",
    "Excel": "Excel",
    "GIF": "GIF",
    "Group": "Gruppe",
    "HTML": "HTML",
    "ID": "ID",
    "Illustrator": "Illustrator",
    "Image": "Bild",
    "InDesign": "InDesign",
    "JPEG": "JPEG",
    "JSON": "JSON",
    "JavaScript": "JavaScript",
    "JavaScript React": "JavaScript-Reaktion",
    "LaTex": "Latex",
    "List": "Auff\u00fchren",
    "Log": "Log",
    "LogEntry": "Log Eintrag",
    "MP3": "MP3",
    "MP4": "MP4",
    "Markdown": "Abschlag",
    "Order": "Auftrag",
    "Order list": "Bestellliste",
    "PDF": "PDF",
    "Permission": "Genehmigung",
    "Photoshop": "Photoshop",
    "PowerPoint": "Steckdose",
    "Python": "Python",
    "Quicktime": "Schnelle Zeit",
    "SCSS": "SCSS",
    "Session": "Session",
    "Swift": "Schnell",
    "Tarball": "Tarball",
    "Text": "Text",
    "ToDo": "Machen",
    "TypeScript": "Typoskript",
    "TypeScript React": "TypeScript React",
    "User": "Benutzer",
    "Vector": "Vektor",
    "Wave": "Welle",
    "Windows Video": "Windows-Video",
    "Word": "Wort",
    "XML": "XML",
    "Zip": "Postleitzahl",
    "abgeschlossen": "abgeschlossen",
    "active": "aktiv",
    "add": "hinzuf\u00fcgen",
    "add contenttype": "Inhaltstyp hinzuf\u00fcgen",
    "add group": "Gruppe hinzuf\u00fcgen",
    "add logentry": "Logeintrag hinzuf\u00fcgen",
    "add order": "Bestellung hinzuf\u00fcgen",
    "add permission": "Berechtigung hinzuf\u00fcgen",
    "add session": "Sitzung hinzuf\u00fcgen",
    "add user": "Nutzer hinzuf\u00fcgen",
    "adjust": "adjust",
    "change": "Ver\u00e4nderung",
    "change contenttype": "Inhaltstyp \u00e4ndern",
    "change group": "Gruppe \u00e4ndern",
    "change logentry": "Logeintrag \u00e4ndern",
    "change order": "Bestellung \u00e4ndern",
    "change permission": "Berechtigung \u00e4ndern",
    "change session": "Sitzung \u00e4ndern",
    "change user": "Benutzer wechseln",
    "clear": "klar",
    "codename": "Code Name",
    "collection": "Sammlung",
    "collections": "Kollektionen",
    "commands": "commands",
    "content": "Inhalt",
    "content type": "Inhaltstyp",
    "create": "erstellen",
    "date joined": "Datum beigetreten",
    "delete": "l\u00f6schen",
    "delete contenttype": "Inhaltstyp l\u00f6schen",
    "delete group": "Gruppe l\u00f6schen",
    "delete logentry": "Logeintrag l\u00f6schen",
    "delete order": "Bestellung l\u00f6schen",
    "delete permission": "Berechtigung l\u00f6schen",
    "delete session": "Sitzung l\u00f6schen",
    "delete user": "Benutzer l\u00f6schen",
    "destroy": "zerst\u00f6ren",
    "detail": "Detail",
    "done": "done",
    "email": "Email",
    "email address": "E-Mail-Addresse",
    "entries": "entries",
    "fetch": "holen",
    "fewer": "weniger",
    "file": "Datei",
    "first name": "Vorname",
    "from other system": "from other system",
    "generate": "generieren",
    "get": "erhalten",
    "greater": "gr\u00f6\u00dfer",
    "group": "Gruppe",
    "groups": "Gruppen",
    "id": "Ich w\u00fcrde",
    "is active": "ist aktiv",
    "is staff": "ist Personal",
    "is superuser": "ist Superuser",
    "last login": "letzte Anmeldung",
    "last name": "Nachname",
    "less": "Weniger",
    "list": "auff\u00fchren",
    "log entry": "Log Eintrag",
    "logentry": "Log Eintrag",
    "mission": "mission",
    "modify": "\u00e4ndern",
    "more": "Mehr",
    "my-route": "meine-route",
    "name": "Name",
    "or": "oder",
    "order": "Auftrag",
    "orders": "orders",
    "orders-detail": "Bestell-Detail",
    "orders-list": "Bestellliste",
    "orders-my-route": "bestell-meine-route",
    "owner": "owner",
    "part": "part",
    "password": "Passwort",
    "permission": "Genehmigung",
    "plays soccer": "plays soccer",
    "remove": "entfernen",
    "roof": "Dach",
    "session": "Session",
    "staff status": "Mitarbeiterstatus",
    "superuser status": "Superuser-Status",
    "system": "system",
    "task": "task",
    "time": "Zeit",
    "to do": "machen",
    "to dos": "to dos",
    "to list": "auflisten",
    "update": "aktualisieren",
    "user": "Benutzer",
    "user permissions": "Benutzerberechtigungen",
    "username": "Nutzername",
    "uses coal": "verwendet Kohle",
    "view contenttype": "Inhaltstyp anzeigen",
    "view group": "Gruppe anzeigen",
    "view logentry": "Logeintrag anzeigen",
    "view order": "Bestellung ansehen",
    "view permission": "Berechtigung anzeigen",
    "view session": "Sitzung ansehen",
    "view user": "Benutzer anzeigen"
}


class MockTranslator:
    @classmethod
    def key_in_translations(cls, key, translations):
        lower_keys = [key.lower() for key in translations.keys()]
        return key.lower() in lower_keys

    def __call__(self, text, *args, **kwargs):
        if self.key_in_translations(text, TRANSLATIONS_DE):
            translations = TRANSLATIONS_DE
        else:
            translations = TRANSLATIONS_EN

        if self.key_in_translations(text, translations):
            lower_translations = {key.lower(): value for key, value in translations.items()}
            return lower_translations[text.lower()]

        return text
